<?php
/**
 * Created by L.
 * Author: wxuns
 * Link: https://www.wxuns.cn
 * Date: 2019/2/19
 * Time: 15:48
 */

namespace Polite\Migration;

class Migration extends \Phpmig\Migration\Migration
{
    protected $schema;

    public function init()
    {
        $this->schema = $this->get('Schema');
        return parent::init(); // TODO: Change the autogenerated stub
    }
}