<?php
/**
 * Created by L.
 * Author: wxuns
 * Link: https://www.wxuns.cn
 * Date: 2018/11/22
 * Time: 14:34
 */

namespace Wxuns\Migration;


use Phinx\Migration\AbstractMigration;

class Migrator extends AbstractMigration
{
    public function table($tableName, $options = [])
    {
        return parent::table($tableName, $options); // TODO: Change the autogenerated stub
    }
}